### ISSUE TITLE
Lab2-ROS-과제 python version issue & arduino library path issue

### ISSUE THREAD

**Issue by nulLeeKH** [UNIST-STEM/.com#1]
*문제*
- arduino를 최초실행해야 라이브러리 디렉토리(~/sketchbook/libraries)가 생김
- make_libraries.py 소스의 버전 의존성 문제가 발생함(작성 환경은 python2, 실습 환경은 python3)

*해결*
1. arduino 명령어로 아두이노 IDE를 한 번 실행시켜야 라이브러리 디렉토리(~/sketchbook/libraries)가 생김

2. /opt/ros/melodic/share/rosserial_arduino/make_libraries.py 내의 print 함수 문법을 python3 문법으로 수정
[74: print(__usage__)]
[81: print("\nExporting to %s" % path)]

3. 기존 명령어(rosrun rosserial_arduino make_libraries.py) 뒤에 아두이노 라이브러리의 path(~/sketchbook/libraries)를 인자로 넘겨줌
[rosrun rosserial_arduino make_libraries.py ~/sketchbook/libraries]

이후 메뉴얼과 같이 수행

**Comment by Esthesia** [comment]
issue website에 반영했습니다.

**Comment by nulLeeKH** [comment]
감사합니다.
